package com.example.cosc341_project.data_classes;

import java.sql.Timestamp;

public class Comment {
    // ATTRIBUTES
    private final int userId;
    private final String text;
    private final Timestamp timestamp;

    // CONSTRUCTORS
    /**
     * This constructor is protected because it is only used in the <code>Post</code> class.
     * It is not intended for use outside of this package. If you want to add comments
     * to a post, you have to do so through the <code>addComment</code> method from the <code>Post</code> class.
     */
    protected Comment(int userId, String text) {
        this.userId = userId;
        this.text = text;
        this.timestamp = new Timestamp(System.currentTimeMillis());
    }

    // GETTERS
    public int getUserId() { return userId; }
    public String getText() { return text; }
    public Timestamp getTimestamp() { return timestamp; }

    // TO STRING (generated by Android Studio)
    @Override
    public String toString() {
        return "Comment{" +
                ", userId=" + userId +
                ", text='" + text + '\'' +
                ", timestamp=" + timestamp +
                '}';
    }
}
