package com.example.cosc341_project.data_classes;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedList;

/**
 * <h4> Notes </h4>
 * <p>
 *     This is a data class for storing information related to posts. It is a supertype of <code>sightingPost</code>
 * </p>
 * <ul>
 *     <li> All attributes are private. </li>
 *     <li>
 *         All attributes have getters.
 *         <b>Please do not modify the values or objects returned by the getters.</b>
 *         Use the setter or other modification method built into the <code>Post</code> class.
 *     </li>
 *     <li>
 *         Not all attributes have setters.
 *         <ul>
 *             <li> <code>UserId</code>, and <code>timestamp</code> are final (immutable) and initialized at construction. </li>
 *             <li> <code>numDislikes</code>, <code>numLikes</code> and <code>comments</code> are initialized as 0, 0 and empty list. These all have <b><i>add</i></b> and <b><i>remove</i></b> methods. </li>
 *             <li> There are no default initialized values for <code>title</code>, <code>description</code> and <code>tags</code>. The user is forced to use their <b><i>setters</i></b> to set these even if they are supposed to be empty. </li>
 *
 *         </ul>
 *     </li>
 * </ul>
 *
 */
public class Post {
    // ATTRIBUTES
    private final int userId;
    private final Timestamp timestamp;

    private String title;
    private String description;
    private String[] tags;

    private int numLikes;
    private int numDislikes;
    private ArrayList<Comment> comments;

    // CONSTRUCTORS
    public Post(int userId) {
        this.userId = userId;
        timestamp = new Timestamp(System.currentTimeMillis());

        numLikes = 0;
        numDislikes = 0;
        comments = new ArrayList<Comment>();
    }

    // GETTERS
    public int getUserId() { return userId; }
    public String getTitle() { return title; }
    public String getDescription() { return description; }
    public Timestamp getTimestamp() { return timestamp; }
    public int getNumLikes() { return numLikes; }
    public int getNumDislikes() { return numDislikes; }
    public String[] getTags() { return tags; }
    public ArrayList<Comment> getComments() { return comments; }

    // SETTERS
    public void setTitle(String title) { this.title = title; }
    public void setDescription(String description) { this.description = description; }
    public void setTags(String[] tags) { this.tags = tags; }

    public void addLike() { numLikes++; }
    public void removeLike() { numLikes--; }
    public void addDislike() { numDislikes++; }
    public void removeDislike() { numDislikes--; }

    /**
     * Adds a comment to this post
     * @param userId id of user making comment
     * @param text Body of the comment
     * @return <code>true</code> if successful, <code>false</code> otherwise
     */
    public boolean addComment(int userId, String text)
    {
        Comment newComment = new Comment(userId, text);
        return comments.add(newComment);
    }

    /**
     * <p> Removes comment at <code>index</code> in <code>comments</code> </p>
     * <p> Throws <code>IndexOutOfBoundsException</code> if unsuccessful </p>
     */
    public void removeComment(int index)
    {
        comments.remove(index);
    }

    // TO STRING (generated by Android Studio)
    @Override
    public String toString() {
        return "Post{" +
                ", userId=" + userId +
                ", timestamp=" + timestamp +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", tags=" + tags +
                ", numLikes=" + numLikes +
                ", numDislikes=" + numDislikes +
                ", comments=" + comments +
                '}';
    }
}

// THOUGHTS
/*
 * The "editing mode" of Evan's stuff will get the whole post object passed to it.
 * Modifications are made, and then that post object is saved using 'saveEditedPost'
 */
